
CREATE TABLE category (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) not null
);

CREATE TABLE expense (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) not null,
created_at date not null,
category int,
amount decimal not null,
FOREIGN KEY (category) REFERENCES category (id)
);