version: '3.8'

services:
  app:
    build: ./
    container_name: app
    ports:
      - '8081:8080'
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: "expenses"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
